name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - comnet

  schedule:
    - cron: '0 12 * * *'  # Trigger automatically at 12:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show Input or Default Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment || 'comnet (default)' }}"
